#!/bin/bash

BLOCKNET_PATH=""

prerequisite(){

  can_run=0

  which docker 1> /dev/null

  if [ ! $? -eq 0 ];then
      sudo apt-get install -y docker.io 
  fi

  which docker-compose 1> /dev/null

  if [ ! $? -eq 0 ];then

    sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose

  fi

  which git 1> /dev/null

  if [ ! $? -eq 0 ];then
    sudo apt-get install -y git
  fi

}

download(){

  git clone https://github.com/hyperledger-fabric/file.git

  mv file/* .

  rm -rf file/

  rm -rf .git/

  # pip install blocknet

  # export BLOCKNET_PATH=`pwd`
}

build_exec_file(){
      echo '''#!/usr/bin/python

import requests
from optparse import OptionParser
from blocknet.bin.fabricnetwork import start


def main():

    try:

        if __name__ == "__main__":
            start()
    except KeyboardInterrupt:
        print("\n")
        pass


main()
    ''' > /usr/local/bin/blocknet

    sudo chmod +x /usr/local/bin/blocknet
    rm -rf blocknet_installer
}

install(){

    prerequisite
    download
    # build_exec_file
}

main(){
  case $1 in
    check-env)
        prerequisite
    ;;
    install)
        install $@
    ;;
  esac


  
}

main $@

