#!/usr/bin/python3
from optparse import OptionParser
import subprocess
from os import sys
from os.path import isfile, expanduser, join


def create_installer_script():
    template = """#!/bin/bash

BLOCKNET_PATH=""

prerequisite(){

  can_run=0

  sudo apt-get update -y

  which docker 1> /dev/null

  if [ ! $? -eq 0 ];then
      sudo apt-get install -y docker.io
  fi

  which docker-compose 1> /dev/null

  if [ ! $? -eq 0 ];then

    sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose

  fi

  which git 1> /dev/null

  if [ ! $? -eq 0 ];then
    sudo apt-get install -y git
  fi

  which pip3 1> /dev/null

  if [ ! $? -eq 0 ];then
    sudo apt-get install -y python3-pip
  fi



}

download(){

  git clone https://github.com/hyperledger-fabric/file.git

  mv file/* .
  rm -rf file/
  rm -rf .git/
  rm -rf images/
  rm -rf README.md

  install_python_package

  export BLOCKNET_PATH=`pwd`
}

install_python_package(){

    echo '''
certifi==2020.6.20
chardet==3.0.4
console==0.990
ezenv==0.91
idna==2.10
pyaml==20.4.0
python-git==2018.2.1
PyYAML==5.3.1
requests==2.24.0
Send2Trash==1.5.0
urllib3==1.25.9
wget==3.2
zipfile36==0.1.3
blocknet
    ''' > packages.txt

    pip3 install -r packages.txt
}

clean(){
    rm -rf installer.sh
    rm -rf packages.txt
}

install(){

    prerequisite
    download
    sudo touch ~/.blocknet
    clean
}

main(){
  case $1 in
    check-env)
        prerequisite
    ;;
    install)
        install $@
    ;;
  esac



}

main $@
        """
    file_name = "installer.sh"
    with open(file_name, "w") as f:
        f.write(template)

    subprocess.call("sudo chmod +x {} ".format(file_name), shell=True)


def run_installer():
    user_home = expanduser("~")
    if not isfile(join(user_home, ".blocknet")):
        create_installer_script()
        subprocess.call("./installer.sh install", shell=True)


def main():

    try:

        if __name__ == "__main__":
            run_installer()
            from blocknet.cli.fabricnetwork import start
            start()
    except KeyboardInterrupt:
        print("\n")
        pass


main()
