#!/bin/bash

MARKSIX_PATH=""

set_python_exec(){

    python3_path=`which python3`

    python_path=`which python`

    sudo unlink $python_path

    sudo ln -s  $python3_path $python_path
}

prerequisite(){

  can_run=0

  which docker 1> /dev/null

  if [ ! $? -eq 0 ];then
      sudo apt-get install -y docker.io 
  fi

  which docker-compose 1> /dev/null

  if [ ! $? -eq 0 ];then

    sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose

  fi

  which git 1> /dev/null

  if [ ! $? -eq 0 ];then
    sudo apt-get install -y git
  fi

  which python3.6 1> /dev/null

  if [ ! $? -eq 0 ];then
 sudo apt-get install -y software-properties-common && sudo add-apt-repository \
 ppa:deadsnakes/ppa && sudo apt-get update && sudo apt-get install -y python3.6
    
  fi

  sudo apt update

  which pip3 1> /dev/null

  if [ ! $? -eq 0 ];then
    sudo apt-get install -y python3-pip
  fi
}

download(){

  git clone https://github.com/eirtscience/marksix.git

  cd marksix 

  MARKSIX_PATH=`pwd`
  
  set_python_exec

  pip3 install -r package.txt

  export $MARKSIX_PATH
}

install(){

  if [ ! -f ".install" ];then
    prerequisite
    download
    touch .install
  fi
}

run(){

  case $1 in
   host)
    ./main.sh all
   ;;
   docker)
    COMPOSE_HTTP_TIMEOUT=100 sudo docker-compose -f docker-compose.yaml up --force-recreate -d
   ;;
  esac
}

main(){
  case $1 in
    check-env)
        prerequisite
    ;;
    install)
        install $@
    ;;

    run)
      shift
      run $@
    ;;
    kill)
      ./main.sh kill
    ;;

  esac


  
}

main $@