#!/bin/bash

prerequisite(){

  can_run=0

  which docker 1> /dev/null

  if [ ! $? -eq 0 ];then
      sudo apt-get install -y docker.io 
  fi

  which docker-compose 1> /dev/null

  if [ ! $? -eq 0 ];then

    sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose

  fi

  which git 1> /dev/null

  if [ ! $? -eq 0 ];then
    sudo apt-get install -y git
  fi

  which python3.6 1> /dev/null

  if [ ! $? -eq 0 ];then
 sudo apt-get install -y software-properties-common && sudo add-apt-repository \
 ppa:deadsnakes/ppa && sudo apt-get update && sudo apt-get install -y python3.6 && sudo apt-get install -y python3-pip
  
  python_path=`which python`
  python6_path=`which python3.6`

  sudo unlink $python_path

  sudo ln -s $python_path $python6_path 

  fi
}

download(){

  git clone https://github.com/eirtscience/marksix.git

  cd marksix

  pip3 install --user -r package.txt 

}

install(){

    prerequisite
    download
}

run(){

  case $2 in
   host)
    ./main.sh all
   ;;
   docker)
    COMPOSE_HTTP_TIMEOUT=100 sudo docker-compose -f docker-compose.yaml up --force-recreate
   ;;
}

main(){
  case $1 in
    check-env)
        prerequisite
    ;;
    install)
        install
    ;;

    run)
      shift
      run $@
    ;;

  esac


  
}

main $@