#!/bin/bash

install(){

  pip install pyunitgen

    sudo echo '''
#!/usr/bin/python3
import sys
from pyunitgen.cli import main


if __name__ == '__main__':

    sys.exit(main())

    ''' > /usr/local/bin/pyunitgen

    sudo chmod +x /usr/local/bin/pyunitgen

    rm -rf pyunitgen

}

install
