#!/bin/bash


prerequisite(){

  can_run=0

  which python3 1> /dev/null

  if [ ! $? -eq 0 ];then
  sudo apt-get install -y software-properties-common && sudo apt-get update && sudo apt-get install -y python3.6
    
  fi

  sudo apt update

  which pip3 1> /dev/null

  if [ ! $? -eq 0 ];then
    sudo apt-get install -y python3-pip
  fi

which python 1> /dev/null

  if [ ! $? -eq 0 ];then

    which python3 1> /dev/null

    if [ $? -eq 0 ];then
       python3_install_dir=`which python3`
       sudo ln -s $python3_install_dir /usr/bin/python
    fi

  fi


}


install(){

  prerequisite

  pip3 install pyunitgen

    sudo echo '''#!/usr/bin/python3
import sys
import os
from pyunitgen.cli import main
sys.path.insert(0,os.getcwd())


if __name__ == "__main__":

    sys.exit(main())

    ''' > /usr/local/bin/pyunitgen && sudo chmod +x /usr/local/bin/pyunitgen && rm -rf pyunitgen
}

install
