#!/bin/bash


prerequisite(){

  can_run=0

  which python3.6 1> /dev/null

  if [ ! $? -eq 0 ];then
 sudo apt-get install -y software-properties-common && sudo add-apt-repository \
 ppa:deadsnakes/ppa && sudo apt-get update && sudo apt-get install -y python3.6
    
  fi

  sudo apt update

  which pip3 1> /dev/null

  if [ ! $? -eq 0 ];then
    sudo apt-get install -y python3-pip
  fi
}


install(){

  prerequisite

 

    sudo echo '''
#!/usr/bin/python3
import sys
from pyunitgen.cli import main


if __name__ == '__main__':

    sys.exit(main())

    ''' > /usr/local/bin/pyunitgen

    sudo chmod +x /usr/local/bin/pyunitgen &&  pip3 install pyunitgen && rm -rf pyunitgen 
}

install
